name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY_RG_NAME: 'bicepregistry'
  REGISTRY_NAME: 'antbicepregistry'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: AzCLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACR_CLIENT_ID }}
          tenant-id: ${{ secrets.ACR_TENANT_ID }}
          subscription-id: ${{ secrets.ACR_SUBSCRIPTION_ID }}

      - name: Deploy
        run: |
          az deployment group create \
            --resource-group ${{ env.REGISTRY_RG_NAME }} \
            --name 'main' \
            --template-file ./deploy/main.bicep \
            --parameters \
              registryName="${{ env.REGISTRY_NAME }}" \
              adminPrincipalId="${{ secrets.ACR_CLIENT_ID }}" \
            --query "properties.outputs"

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: AzCLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACR_CLIENT_ID }}
          tenant-id: ${{ secrets.ACR_TENANT_ID }}
          subscription-id: ${{ secrets.ACR_SUBSCRIPTION_ID }}

      - name: Publish modules
        run: |
          az bicep publish --file ./modules/bicep-on-k8s/main.bicep --target "br:${{ env.REGISTRY_NAME }}.azurecr.io/bicep-on-k8s:0.1"
          az bicep publish --file ./modules/empty/main.bicep --target "br:${{ env.REGISTRY_NAME }}.azurecr.io/empty:0.1"
          az bicep publish --file ./modules/javascript/main.bicep --target "br:${{ env.REGISTRY_NAME }}.azurecr.io/javascript:0.1"